name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
        - 'bots/*'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'bots/*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: bots
      run: docker build . --file Dockerfile --tag inquireai:$(date +%s)
